# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build environment
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Sphinx configuration
sphinx:
  configuration: module_4/docs/conf.py

# Python environment setup
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Mock heavy or unavailable modules during build
# This is important for psycopg or other DB packages
# so that autodoc imports succeed
python:
  system_site_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
  environment:
    # Example: Mock psycopg so RTD can build docs without a DB
    RTD_MOCK_MODULES: psycopg,psycopg2
