import pytest
import psycopg2
from module_4.src.app.app import app as flask_app

@pytest.fixture
def app():
    flask_app.config.update({"TESTING": True})
    return flask_app


@pytest.fixture
def client(app):
    return app.test_client()

@pytest.fixture
def example_applicant_data():
    return [
        {
            "program": "Computer Science, Johns Hopkins University",
            "comments": "Masters in Comupter Science at JHU",
            "date_added": "Added on January 1, 2021",
            "url": "https://www.thegradcafe.com/survey/result/123456",
            "status": "Accepted on 20 Dec",
            "term": "Fall 2021",
            "US/International": "American",
            "GPA": "3.13",
            "Degree": "Masters"
        },
        {
            "program": "Accounting, University Of Maryland",
            "comments": "Money money money",
            "date_added": "Added on February 2, 2022",
            "url": "https://www.thegradcafe.com/survey/result/234567",
            "status": "Accepted on 18 Jan",
            "term": "Fall 2022",
            "US/International": "International",
            "GPA": "3.85",
            "Degree": "PhD"
        },
        {
            "program": "Nursing, Towson University",
            "comments": "I am nurse",
            "date_added": "Added on March 3, 2023",
            "url": "https://www.thegradcafe.com/survey/result/345678",
            "status": "Rejected on 31 Jan",
            "term": "Fall 2023",
            "US/International": "American",
            "GPA": "3.17",
            "Degree": "Other"
        }
    ]

@pytest.fixture
def example_duplicate_applicant_data():
    return [
        {
            "program": "Computer Science, Johns Hopkins University",
            "comments": "Masters in Comupter Science at JHU",
            "date_added": "Added on January 1, 2021",
            "url": "https://www.thegradcafe.com/survey/result/123456",
            "status": "Accepted on 20 Dec",
            "term": "Fall 2021",
            "US/International": "American",
            "GPA": "3.13",
            "Degree": "Masters"
        },
        {
            "program": "Computer Science, Johns Hopkins University",
            "comments": "Masters in Comupter Science at JHU",
            "date_added": "Added on January 1, 2021",
            "url": "https://www.thegradcafe.com/survey/result/123456",
            "status": "Accepted on 20 Dec",
            "term": "Fall 2021",
            "US/International": "American",
            "GPA": "3.13",
            "Degree": "Masters"
        }
    ]

@pytest.fixture
def connect_to_db():
    conn = psycopg2.connect(
        dbname="postgres",
        user="postgres",
        host="localhost",
        port=5432
    )
    cur = conn.cursor()
    cur.execute("""
                CREATE TABLE test (
                p_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                program TEXT,
                comments TEXT,
                date_added DATE,
                url TEXT UNIQUE,
                status TEXT,
                term TEXT,
                us_or_international TEXT,
                gpa FLOAT,
                gre FLOAT,
                gre_v FLOAT,
                gre_aw FLOAT,
                degree TEXT,
                llm_generated_program TEXT,
                llm_generated_university TEXT);
                """
                )
    conn.commit()
    yield conn, cur

    cur.execute("DROP TABLE IF EXISTS test")
    conn.commit()
    cur.close()
    conn.close()