name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    strategy:
      matrix:
        python-version: ["3.11"]  # Test with just one version first

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Debug - List files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in root:"
        ls -la
        echo "Python path:"
        python -c "import sys; print('\n'.join(sys.path))"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug - Test imports
      run: |
        python -c "import psycopg; print('psycopg imported successfully')"
        python -c "import flask; print('flask imported successfully')"
        python -c "import pytest; print('pytest imported successfully')"

    - name: Debug - Database connection
      env:
        DATABASE_URL: postgresql://postgres@localhost:5432/postgres
      run: |
        python -c "
        import os
        import psycopg
        print(f'DATABASE_URL: {os.environ.get(\"DATABASE_URL\")}')
        try:
            conn = psycopg.connect(os.environ.get('DATABASE_URL'))
            print('Database connection successful')
            conn.close()
        except Exception as e:
            print(f'Database connection failed: {e}')
        "

    - name: Run tests with full output
      env:
        DATABASE_URL: postgresql://postgres@localhost:5432/postgres
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "Running tests..."
        pytest -q --cov=module_4/src --cov-report=term-missing --cov-fail-under=100