name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for Postgres
      run: |
        echo "Waiting for Postgres to be ready..."
        for i in {1..30}; do
          pg_isready -h localhost -p 5432 -U postgres && break
          echo "Postgres not ready yet... waiting 1s"
          sleep 1
        done
      env:
        PGPASSWORD: postgres

    - name: Debug - Database connection
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      run: |
        python -c "
        import os
        import psycopg
        print(f'DATABASE_URL={os.environ.get(\"DATABASE_URL\")}')
        try:
            conn = psycopg.connect(os.environ.get('DATABASE_URL'))
            print('Database connection successful')
            conn.close()
        except Exception as e:
            print(f'Database connection failed: {e}')
        "

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "Running tests..."
        pytest -v --capture=tee-sys --cov=module_4/src --cov-report=term-missing --cov-fail-under=100
